
ENVIRONMENT_MOBILE_APP_LOCATION = "/private/tmp/theLott_6.2.2.app"
ENVIRONMENT_MOBILE_PLATFORM_NAME = 'iOS'
ENVIRONMENT_MOBILE_PLATFORM_VERSION = "12.1"
ENVIRONMENT_MOBILE_SIMULATOR = "iPhone XS"
APP_USER='preet@dummyemail.com'
APP_PASSWORD='Password123'
# Appium Server Config
HOST = "0.0.0.0"
PORT = "4723"